#!/usr/bin/env python3
"""STAGE 5: render the EgoDex atlas (EN + CN) using the shared atlas_lib.

EgoDex-specific panel covers tasks, reversible task pairs, manipulated objects,
and capture environments. Example media is link-only (no permissively
inline-able frame; EgoDex is CC BY-NC-ND, used internally here).
"""
from __future__ import annotations

import datetime
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import atlas_lib as A  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
SLUG = "egodex"

stats = json.load(open(os.path.join(HERE, f"{SLUG}_stats.json"), encoding="utf-8"))
cdoc = json.load(open(os.path.join(HERE, f"{SLUG}_clusters.json"), encoding="utf-8"))
scatter = json.load(open(os.path.join(HERE, f"{SLUG}_scatter.json"), encoding="utf-8"))
prov = json.load(open(os.path.join(HERE, "download_provenance.json"), encoding="utf-8"))
df_path = os.path.join(HERE, f"{SLUG}_annotations.parquet")

CLUSTERS = cdoc["clusters"]
CFG = cdoc["config"]
POINTS = scatter["points"]
ACCESS = prov.get("access_utc", "")[:10]
BUILD = datetime.date.today().isoformat()

REPO = "https://github.com/apple/ml-egodex"
ARXIV = "https://arxiv.org/abs/2505.11709"
VIEWER = "https://huggingface.co/spaces/pablovela5620/ego-dex-viewer"
LICENSE_URL = "https://creativecommons.org/licenses/by-nc-nd/4.0/"
# CC BY-NC-ND: link the teaser figure, never embed/redistribute it (no derivatives).
EXAMPLE_IMG_URL = "https://arxiv.org/html/2505.11709v2/x1.png"

# reversible example pairs (active vs alternate direction) from the parquet
REV_PAIRS = []
try:
    import pandas as pd
    _df = pd.read_parquet(df_path, columns=["text", "alt_description", "llm_type"])
    _rev = _df[(_df["llm_type"].astype(str).str.lower() == "reversible")
               & (_df["alt_description"].astype(str).str.len() > 0)]
    seen = set()
    for _, r in _rev.iterrows():
        key = tuple(sorted([str(r["text"]), str(r["alt_description"])]))
        if key in seen:
            continue
        seen.add(key)
        REV_PAIRS.append((str(r["text"]), str(r["alt_description"])))
        if len(REV_PAIRS) >= 6:
            break
except Exception:
    REV_PAIRS = []

META = {
    "name": "EgoDex",
    "usage": ["corpus", "hand-pose", "vla-pretrain"],
    "downstream": [],
    "annotation_types": ["task-instruction"],
    "source_datasets": ["EgoDex (Apple Vision Pro capture)"],
    "links": {"repo": REPO, "paper": ARXIV, "project": VIEWER, "license": LICENSE_URL},
    "license_name": "CC BY-NC-ND 4.0 (internal use)",
    "citation": "Hoque et al., EgoDex: Learning Dexterous Manipulation from Large-Scale "
                "Egocentric Video, ICLR 2026 (arXiv:2505.11709).",
    "commit": prov.get("split", "test") + " split", "access": ACCESS, "build_date": BUILD,
}

WORK_I18N = {
    "en": {
        "page_title": "EgoDex · Ego Language-Annotation Atlas",
        "k_ann": "episodes (test)", "k_unique": "unique instructions",
        "k_clusters": "clusters", "k_meanlen": "mean length (tokens)",
        "k_tasks": "tasks", "k_verbs": "verbs", "k_objects": "objects",
        "k_rev": "reversible share",
        "media_caption": "EgoDex: 829 hours of Apple Vision Pro egocentric manipulation with 3D hand pose.",
        "media_credit": "EgoDex, Hoque et al., ICLR 2026 (CC BY-NC-ND, internal analysis).",
        "focus": ("Per-episode task instructions over Apple Vision Pro egocentric "
                  "manipulation with native 3D hand pose, here the test split, with "
                  "reversible tasks carrying both directions."),
        "datapath": ("EgoDex captures egocentric manipulation with Apple Vision Pro, pairing "
                     "video and native 3D hand pose with a per-episode task instruction "
                     "generated by an LLM and stored as an HDF5 attribute. This atlas reads "
                     "the instruction attributes from the test split (no video downloaded) "
                     "and clusters the active instruction per episode. Reversible tasks store "
                     "both directions (for example add a lid versus remove a lid); the "
                     "direction actually performed is selected per episode."),
        "flow": ["Apple Vision Pro capture", "video + 3D hand pose (HDF5)",
                 "LLM task instruction per episode", "dexterous manipulation learning"],
        "cited_note": ("Per the paper: 829 hours, 194 tasks, native 3D hand pose. This atlas "
                       "reads the test split: " + f"{stats['counts']['labelled_segments']:,} "
                       "episodes, " + f"{stats['counts']['unique_narrations_clean']:,} unique "
                       "instructions, " + f"{stats['counts']['tasks']} tasks, from the "
                       "downloaded HDF5 attributes."),
        "sec_tasks": "Tasks, objects and environments",
        "tasks_help": ("EgoDex instructions are organized by task, with reversible tasks "
                       "carrying both directions. Counts come from the downloaded attributes."),
        "top_tasks": "top tasks (by episode)", "objects_lbl": "top objects",
        "env_lbl": "capture environments (table)", "rev_lbl": "reversible task pairs",
    },
    "cn": {
        "page_title": "EgoDex · 第一人称语言标注图谱",
        "k_ann": "片段（测试集）", "k_unique": "唯一指令",
        "k_clusters": "聚类数", "k_meanlen": "平均长度（token）",
        "k_tasks": "任务", "k_verbs": "动词", "k_objects": "物体",
        "k_rev": "可逆占比",
        "media_caption": "EgoDex：829 小时 Apple Vision Pro 第一人称操作，带三维手部姿态。",
        "media_credit": "EgoDex，Hoque 等，ICLR 2026（CC BY-NC-ND，内部分析）。",
        "focus": ("基于 Apple Vision Pro 第一人称操作的逐片段任务指令，"
                  "带原生三维手部姿态，此处为测试集，可逆任务包含正反两个方向。"),
        "datapath": ("EgoDex 使用 Apple Vision Pro 采集第一人称操作，将视频与原生三维手部"
                     "姿态同每个片段一条由大模型生成、并以 HDF5 属性形式存储的任务指令配对。"
                     "本图谱仅读取测试集的指令属性（不下载视频），并对每个片段的有效指令"
                     "进行聚类。可逆任务存有正反两个方向（例如盖上盖子与取下盖子）；实际"
                     "执行的方向按片段选定。"),
        "flow": ["Apple Vision Pro 采集", "视频 + 三维手部姿态（HDF5）",
                 "逐片段大模型任务指令", "灵巧操作学习"],
        "cited_note": ("论文数据：829 小时、194 个任务、原生三维手部姿态。本图谱读取测试集："
                       + f"{stats['counts']['labelled_segments']:,} 个片段、"
                       + f"{stats['counts']['unique_narrations_clean']:,} 条唯一指令、"
                       + f"{stats['counts']['tasks']} 个任务，来自下载的 HDF5 属性。"),
        "sec_tasks": "任务、物体与环境",
        "tasks_help": ("EgoDex 指令按任务组织，可逆任务包含正反两个方向。计数来自下载的属性。"),
        "top_tasks": "高频任务（按片段）", "objects_lbl": "高频物体",
        "env_lbl": "采集环境（桌面）", "rev_lbl": "可逆任务对",
    },
}


def kc_list(t):
    c, ln, cl = stats["counts"], stats["length"], stats["clusters"]
    return [
        (f'{c["labelled_segments"]:,}', t["k_ann"]),
        (f'{c["unique_narrations_clean"]:,}', t["k_unique"]),
        (f'{cl["n_clusters"]}', t["k_clusters"]),
        (f'{ln["tokens_mean"]:.1f}', t["k_meanlen"]),
        (f'{c["tasks"]}', t["k_tasks"]),
        (f'{c["distinct_verbs"]}', t["k_verbs"]),
        (f'{c["distinct_objects"]}', t["k_objects"]),
        (f'{c["reversible_share"]*100:.0f}%', t["k_rev"]),
    ]


def usage_body(t):
    media = (f'<div class="minihead">{A.esc(t["sec_media"])}</div>'
             + A.media_panel(t, image_uri=None, image_url=EXAMPLE_IMG_URL,
                             video_url=VIEWER, page_url=REPO,
                             caption=t["media_caption"], credit=t["media_credit"]))
    return media + f'<p class="prose">{A.esc(t["datapath"])}</p>' + A.flow_diagram(t["flow"])


def gran_body(t):
    ln = stats["length"]
    den = stats.get("density", {})
    hist = ln.get("token_hist", [])
    cells = [
        (f'{den.get("episodes_per_task", 0):.0f}', t["per_video"] if False else ("episodes / task" if t is WORK_I18N["en"] else "每任务片段")),
        (f'{ln["tokens_median"]:.0f}', t["median_len"]),
        (f'{ln["tokens_p90"]:.0f}', t["p90_len"]),
        (f'{ln["tokens_max"]}', t["max_len"]),
    ]
    kc = "".join(f'<div class="kc"><div class="kcv">{v}</div><div class="kcl">{A.esc(l)}</div></div>'
                 for v, l in cells)
    return (
        '<div class="twocol"><div>'
        f'<div class="minihead">{A.esc(t["len_hist"])}</div>'
        f'{A.bar_rows([(str(k), v) for k, v in hist])}'
        '</div><div>'
        f'<div class="kcgrid small">{kc}</div>'
        f'<div class="tierbox"><span class="ck">{A.esc(t["gran_tier"])}:</span> {A.esc(stats["granularity_tier"])}</div>'
        '</div></div>'
    )


def vn_body(t):
    words = [(w, c) for w, c in stats["word_top"]][:24]
    ww = " ".join(f'<span class="word">{A.esc(w)} <i>{c:,}</i></span>' for w, c in words)
    return (
        '<div class="twocol">'
        f'<div><div class="minihead">{A.esc(t["top_verbs"])}</div>{A.bar_rows(stats["verb_top"][:18], color="var(--accent)")}</div>'
        f'<div><div class="minihead">{A.esc(t["top_nouns"])}</div>{A.bar_rows(stats["noun_top"][:18], color="var(--accent2)")}</div>'
        '</div>'
        f'<div class="minihead">{A.esc(t["top_words"])}</div><div class="wordwrap">{ww}</div>'
    )


def tasks_body(t):
    rev = ""
    if REV_PAIRS:
        items = "".join(f'<li><span class="tag">{A.esc(t["rev_lbl"])}</span>'
                        f'{A.esc(a)} &harr; {A.esc(b)}</li>' for a, b in REV_PAIRS)
        rev = f'<div class="minihead">{A.esc(t["rev_lbl"])}</div><ul class="exlist">{items}</ul>'
    return (
        '<div class="twocol"><div>'
        f'<div class="minihead">{A.esc(t["top_tasks"])}</div>'
        f'{A.bar_rows(stats.get("task_top", [])[:16], color="#319795")}'
        '</div><div>'
        f'<div class="minihead">{A.esc(t["env_lbl"])}</div>'
        f'{A.bar_rows(stats.get("env_table_dist", [])[:10], color="#805ad5")}'
        '</div></div>'
        + rev
    )


def cfg_desc():
    uv, uc, hp = CFG["umap_viz"], CFG["umap_cluster"], CFG["hdbscan"]
    return {
        "encoder": CFG["encoder"],
        "reducer_desc": (f'{CFG["reducer"].upper()} viz(2D, n_neighbors={uv["n_neighbors"]}, '
                         f'min_dist={uv["min_dist"]}, {uv["metric"]}), cluster({uc["n_components"]}D)'),
        "cluster_desc": (f'HDBSCAN(min_cluster_size={hp["min_cluster_size"]}, '
                         f'min_samples={hp["min_samples"]}), {cdoc["n_clusters"]} clusters, '
                         f'noise {cdoc["noise_share_weighted"]*100:.1f}%'),
    }


def build(lang):
    t = dict(A.CHROME[lang])
    t.update(WORK_I18N[lang])
    t["other_file"] = f"{SLUG}_atlas{'_cn' if lang == 'en' else ''}.html"
    body = (
        A.header(META, t, kc_list(t))
        + A.sec("01", t["sec_usage"], usage_body(t))
        + A.sec("02", t["sec_scatter"], A.scatter_body(t), t["scatter_help"])
        + A.sec("03", t["sec_clusters"], A.cluster_body(t, CLUSTERS))
        + A.sec("04", t["sec_gran"], gran_body(t))
        + A.sec("05", t["sec_vn"], vn_body(t))
        + A.sec("06", t["sec_tasks"], tasks_body(t), t["tasks_help"])
        + A.sec("07", t["sec_drawer"], A.drawer_body(t), t["drawer_help"])
        + A.footer("08", META, t, cfg_desc())
    )
    data = A.data_scripts(POINTS, CLUSTERS, A.ljs_from(t))
    return A.page(lang, t, body, data)


def main():
    for lang, suffix in (("en", "_atlas"), ("cn", "_atlas_cn")):
        out = os.path.join(HERE, f"{SLUG}{suffix}.html")
        with open(out, "w", encoding="utf-8") as fh:
            fh.write(build(lang))
        print(f"wrote {out}  ({os.path.getsize(out)/1024:.0f} KB)")


if __name__ == "__main__":
    main()
