#!/usr/bin/env python3
"""Regenerate the collection landing page (index.html) and the README survey
table + roadmap from per-entry manifests. Keeps the dashboard from desyncing:
run this whenever an atlas is added or rebuilt.

Inputs:
  */atlas_entry.json   one per work (status: built | planned), counts pulled
                       from each built entry's stats_file
  roadmap.json         optional: researched-but-not-built works (planned)

Outputs:
  index.html           landing page + survey dashboard (blueprint style, offline)
  README.md            SURVEY and ROADMAP blocks rewritten between markers
"""
from __future__ import annotations

import datetime
import glob
import html
import json
import os

import atlas_lib as A

HERE = os.path.dirname(os.path.abspath(__file__))
BUILD_DATE = datetime.date.today().isoformat()

TIER_ORDER = ["corpus", "dataset", "dense-relabel", "world-model", "vla-pretrain",
              "co-train", "affordance", "reward-repr", "perception-pretrain",
              "hand-pose", "eval-benchmark", "annotation-pipeline"]
TIER_LABEL = {
    "corpus": "Corpora (language supervision sources)",
    "dataset": "Datasets",
    "dense-relabel": "Dense relabeling",
    "world-model": "World / video models",
    "vla-pretrain": "VLA / policy pretraining",
    "co-train": "Human + robot co-training",
    "affordance": "Affordance / interaction priors",
    "reward-repr": "Reward / representation learning",
    "perception-pretrain": "Perception pretraining",
    "hand-pose": "Hand-pose supervision",
    "eval-benchmark": "Evaluation benchmarks",
    "annotation-pipeline": "Annotation pipelines",
}
CAT_ORDER = ["corpus", "dataset", "dense-annotation", "method"]
CAT_LABEL = {"corpus": "Corpora with real language annotations",
             "dataset": "Datasets", "dense-annotation": "Dense-annotation works",
             "method": "Methods that define how human video is used"}

TIER_LABEL_CN = {
    "corpus": "语料库（语言监督来源）", "dataset": "数据集", "dense-relabel": "稠密再标注",
    "world-model": "世界 / 视频模型", "vla-pretrain": "VLA / 策略预训练",
    "co-train": "人类 + 机器人协同训练", "affordance": "可供性 / 交互先验",
    "reward-repr": "奖励 / 表征学习", "perception-pretrain": "感知预训练",
    "hand-pose": "手部姿态监督", "eval-benchmark": "评测基准", "annotation-pipeline": "标注流程",
}
CAT_LABEL_CN = {"corpus": "含真实语言标注的语料库", "dataset": "数据集",
                "dense-annotation": "稠密标注工作", "method": "定义人类视频使用方式的方法"}

INDEX_I18N = {
    "en": {
        "lang_name": "English", "other_name": "中文", "other_file": "index_cn.html",
        "title": "Ego Language-Annotation Atlas", "brand": "Ego Language-Annotation Atlas",
        "focus": ("A curated, side-by-side survey of egocentric human-video works: how each "
                  "uses human data, and what its language supervision actually looks like once "
                  "the real annotation strings are downloaded and clustered. Every statistic "
                  "traces to downloaded data or a cited source."),
        "k_built": "built atlases", "k_desc": "descriptive entries",
        "k_plan": "on the roadmap", "k_gen": "generated",
        "note": ("Hand-compiled reference over downloaded data, may contain errors. Open an "
                 "issue to fix it. No em-dashes, blueprint house style."),
        "s_entries": "Entries", "s_survey": "Survey table",
        "s_built": "Built atlases", "s_desc": "Descriptive entries",
        "s_cross": "Cross-work comparison", "s_road": "Roadmap (researched, not yet built)",
        "th_work": "work", "th_type": "type", "th_usage": "usage",
        "th_annot": "annotation types", "th_ann": "annotations", "th_clusters": "clusters",
        "th_data": "data", "th_license": "license", "th_atlas": "atlas",
        "descriptive": "descriptive", "license_lbl": "license",
        "lk_atlas_en": "atlas EN", "lk_atlas_cn": "中文", "lk_paper": "paper", "lk_data": "data",
        "u_ann": "annotations", "u_clusters": "clusters", "u_hr": "/hr", "u_h": "h",
        "cross_none": ("The cross-work coverage matrix and vocabulary-overlap comparison "
                       "activate once a second atlas is built."),
        "cross_matrix": "work x verb-family coverage (% of annotations)",
        "cross_gran": "granularity contrast (mean narration length, tokens)",
        "cross_overlap": "lexical overlap (Jaccard, top-25 class keys)",
        "cross_pair": "pair", "cross_verbs": "verbs", "cross_nouns": "nouns",
        "cross_usage": "usage-method and annotation-style",
        "road_none": "Roadmap is empty.",
        "road_access": "access", "road_license": "license",
        "footer": ("Generated by build_atlas_index.py on {date}. Each entry is reproducible "
                   "from its folder: pip install -r requirements.txt, then python "
                   "build_&lt;slug&gt;.py."),
    },
    "cn": {
        "lang_name": "中文", "other_name": "English", "other_file": "index.html",
        "title": "第一人称语言标注图谱", "brand": "第一人称语言标注图谱",
        "focus": ("一份对第一人称人类视频工作的精选并列综述：每项工作如何使用人类数据，"
                  "以及在下载真实标注字符串并聚类之后，其语言监督究竟是什么样子。每一项"
                  "统计都可追溯到下载的数据或引用来源。"),
        "k_built": "已构建图谱", "k_desc": "描述性条目",
        "k_plan": "路线图中", "k_gen": "生成于",
        "note": ("基于下载数据手工整理的参考资料，可能存在错误。欢迎提交 issue 修正。"
                 "不使用长破折号，蓝图风格。"),
        "s_entries": "条目", "s_survey": "综述表",
        "s_built": "已构建图谱", "s_desc": "描述性条目",
        "s_cross": "跨工作对比", "s_road": "路线图（已调研，尚未构建）",
        "th_work": "工作", "th_type": "类型", "th_usage": "使用方式",
        "th_annot": "标注类型", "th_ann": "标注数", "th_clusters": "聚类数",
        "th_data": "数据", "th_license": "许可", "th_atlas": "图谱",
        "descriptive": "描述性", "license_lbl": "许可",
        "lk_atlas_en": "图谱 EN", "lk_atlas_cn": "中文", "lk_paper": "论文", "lk_data": "数据",
        "u_ann": "标注", "u_clusters": "聚类", "u_hr": "/小时", "u_h": "小时",
        "cross_none": ("跨工作覆盖矩阵与词汇重叠对比将在构建第二个图谱后启用。"),
        "cross_matrix": "工作 x 动词大类覆盖（占标注百分比）",
        "cross_gran": "粒度对比（旁白平均长度，token）",
        "cross_overlap": "词汇重叠（Jaccard，前 25 类别键）",
        "cross_pair": "配对", "cross_verbs": "动词", "cross_nouns": "名词",
        "cross_usage": "使用方式与标注风格",
        "road_none": "路线图为空。",
        "road_access": "获取", "road_license": "许可",
        "footer": ("由 build_atlas_index.py 于 {date} 生成。每个条目均可从其文件夹复现："
                   "pip install -r requirements.txt，然后 python build_&lt;slug&gt;.py。"),
    },
}


def tier_label(t, lang):
    return (TIER_LABEL_CN if lang == "cn" else TIER_LABEL).get(t, t)


def cat_label(c, lang):
    return (CAT_LABEL_CN if lang == "cn" else CAT_LABEL).get(c, c)


def esc(s):
    return html.escape(str(s), quote=True)


def chip(s):
    return f'<span class="chip">{esc(s)}</span>'


def load_entries():
    entries = []
    for path in sorted(glob.glob(os.path.join(HERE, "*", "atlas_entry.json"))):
        e = json.load(open(path, encoding="utf-8"))
        if e.get("status") not in ("built", "descriptive"):
            continue
        if e.get("status") == "built" and e.get("stats_file"):
            sp = os.path.join(HERE, e["stats_file"])
            if os.path.exists(sp):
                st = json.load(open(sp, encoding="utf-8"))
                dens_d = st.get("density", {}) or {}
                hrs_d = st.get("hours", {}) or {}
                dens = (dens_d.get("segments_per_hour_labelled")
                        or dens_d.get("segments_per_hour_cited") or 0)
                hrs = (hrs_d.get("total_hours_all_videos")
                       or hrs_d.get("annotated_span_hours") or 0)
                e["_counts"] = {
                    "annotations": st["counts"].get("labelled_segments", "n/a"),
                    "clusters": st.get("clusters", {}).get("n_clusters", "n/a"),
                    "density": round(dens),
                    "hours": hrs,
                    "unique": st["counts"].get("unique_narrations_clean", "n/a"),
                }
                e["_stats"] = st
        entries.append(e)
    return entries


def load_roadmap():
    p = os.path.join(HERE, "roadmap.json")
    if os.path.exists(p):
        return json.load(open(p, encoding="utf-8")).get("planned", [])
    return []


def _norm(s):
    return "".join(ch for ch in str(s).lower() if ch.isalnum())


def filter_planned(planned, entries):
    """Drop roadmap works that now have an entry (built or descriptive)."""
    done = {_norm(e["name"]) for e in entries}
    return [p for p in planned if _norm(p["name"]) not in done]


def primary_tier(e):
    for t in TIER_ORDER:
        if t in e.get("usage_methods", []):
            return t
    um = e.get("usage_methods") or ["dataset"]
    return um[0]


# ------------------------------------------------------------------ index.html
CSS = r"""
:root{--paper:#e9edf4;--ink:#15233e;--muted:#5d6c87;--line:#c4d0e2;--accent:#1f4e9b;--accent2:#b45309}
*{box-sizing:border-box}body{margin:0;font-family:"JetBrains Mono",ui-monospace,Consolas,Menlo,monospace;
color:var(--ink);background-color:var(--paper);font-size:13px;line-height:1.5;
background-image:linear-gradient(rgba(110,135,175,.10) 1px,transparent 1px),linear-gradient(90deg,rgba(110,135,175,.10) 1px,transparent 1px),linear-gradient(rgba(110,135,175,.18) 1px,transparent 1px),linear-gradient(90deg,rgba(110,135,175,.18) 1px,transparent 1px);
background-size:24px 24px,24px 24px,120px 120px,120px 120px}
a{color:var(--accent);text-decoration:none;border-bottom:1px dotted var(--accent)}a:hover{border-bottom-style:solid}
.wrap{max-width:1080px;margin:0 auto;padding:18px 16px 64px}
.card{background:rgba(255,255,255,.80);border:1px solid var(--line);padding:16px 18px;margin:14px 0}
h1{font-size:28px;letter-spacing:.04em;margin:2px 0 4px}
.brand{font-size:11px;text-transform:uppercase;letter-spacing:.22em;color:var(--muted)}
.toprow{display:flex;justify-content:space-between;align-items:center}
.langtoggle a{font-size:12px}
.focus{max-width:74ch;color:var(--ink)}
.minihead{font-size:11px;text-transform:uppercase;letter-spacing:.1em;color:var(--muted);margin:14px 0 6px}
.twocol{display:grid;grid-template-columns:1fr 1fr;gap:22px}
.dtable{width:100%;border-collapse:collapse;font-size:11.5px}
.dtable th,.dtable td{border-bottom:1px solid var(--line);padding:4px 7px;text-align:left}
.dtable th.num,.dtable td.num{text-align:right;font-variant-numeric:tabular-nums}
.dtable td.lab{font-weight:600;white-space:nowrap}
.bar{display:grid;grid-template-columns:150px 1fr 56px;gap:8px;align-items:center;margin:3px 0}
.bk{font-size:11px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.bt{background:#dde6f2;height:12px;border:1px solid var(--line)}.bf{display:block;height:100%}
.bv{font-size:11px;text-align:right;color:var(--muted);font-variant-numeric:tabular-nums}
@media(max-width:680px){.twocol{grid-template-columns:1fr}}
h2{font-size:13px;text-transform:uppercase;letter-spacing:.14em;border-bottom:1px solid var(--line);padding-bottom:7px;margin:0 0 12px}
h3{font-size:12px;text-transform:uppercase;letter-spacing:.1em;color:var(--accent);margin:16px 0 8px}
.snum{color:var(--accent);margin-right:6px}
.chip{display:inline-block;border:1px solid var(--accent);color:var(--accent);border-radius:11px;padding:0 8px;font-size:11px;margin:1px 2px}
.chip.alt{border-color:var(--accent2);color:var(--accent2)}
.chip.plan{border-color:var(--muted);color:var(--muted)}
.note{font-size:11px;color:var(--muted);border-left:2px solid var(--line);padding-left:8px;margin:10px 0 0}
.kc{display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:8px;margin:10px 0}
.kc div{border:1px solid var(--line);background:rgba(255,255,255,.55);padding:6px 8px}
.kcv{font-size:17px;font-weight:700;color:var(--accent)}.kcl{font-size:10px;color:var(--muted);text-transform:uppercase;letter-spacing:.05em}
.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:12px}
.entry{border:1px solid var(--line);background:rgba(255,255,255,.6);padding:12px 14px;display:flex;flex-direction:column;gap:6px}
.entry h4{margin:0;font-size:16px}.entry .ef{font-size:12px;color:var(--ink)}
.entry .em{font-size:11px;color:var(--muted)}
.entry .lk{margin-top:auto;font-size:12px}
table{width:100%;border-collapse:collapse;font-size:11.5px}
th,td{border-bottom:1px solid var(--line);padding:5px 7px;text-align:left;vertical-align:top}
th{font-size:10px;text-transform:uppercase;letter-spacing:.05em;color:var(--muted);background:#eef2f8}
.tablewrap{overflow-x:auto;border:1px solid var(--line)}
.built{color:var(--accent);font-weight:700}.plan{color:var(--muted)}
.rm{font-size:12px;margin:5px 0;padding:7px 9px;border:1px solid var(--line);background:rgba(255,255,255,.5)}
.rm b{font-size:13px}.rm .meta{color:var(--muted);font-size:11px}
@media(max-width:680px){.cards{grid-template-columns:1fr}}
"""


def entry_card(e, t):
    c = e.get("_counts", {})
    badge = "" if e.get("status") == "built" else f' <span class="chip plan">{esc(t["descriptive"])}</span>'
    counts = ""
    if c and isinstance(c.get("annotations"), int):
        counts = (f'<div class="em">{c["annotations"]:,} {esc(t["u_ann"])} &middot; '
                  f'{c["clusters"]} {esc(t["u_clusters"])} &middot; {c["density"]:,}{esc(t["u_hr"])} &middot; '
                  f'{c["hours"]:.1f} {esc(t["u_h"])}</div>')
    um = " ".join(chip(u) for u in e.get("usage_methods", []))
    at = " ".join(chip(a) for a in e.get("annotation_types", []))
    links = []
    lk = e.get("links", {})
    if lk.get("atlas_en"):
        links.append(f'<a href="{lk["atlas_en"]}">{esc(t["lk_atlas_en"])}</a>')
    if lk.get("atlas_cn"):
        links.append(f'<a href="{lk["atlas_cn"]}">{esc(t["lk_atlas_cn"])}</a>')
    if lk.get("paper"):
        links.append(f'<a href="{lk["paper"]}">{esc(t["lk_paper"])}</a>')
    if lk.get("repo"):
        links.append(f'<a href="{lk["repo"]}">{esc(t["lk_data"])}</a>')
    return (
        '<div class="entry">'
        f'<h4>{esc(e["name"])}{badge}</h4>'
        f'<div class="ef">{esc(e.get("focus", ""))}</div>'
        f'<div>{um} {at}</div>'
        f'{counts}'
        f'<div class="em">{esc(t["license_lbl"])}: {esc(e.get("license", "n/a"))}</div>'
        f'<div class="lk">{" &middot; ".join(links)}</div>'
        '</div>'
    )


def survey_rows_html(entries, planned, t):
    rows = []
    for e in entries:
        c = e.get("_counts", {})
        lk = e.get("links", {})
        ann = c.get("annotations")
        ann_s = f"{ann:,}" if isinstance(ann, int) else "n/a"
        clu = c.get("clusters")
        clu_s = f"{clu}" if isinstance(clu, int) else "n/a"
        atlas = (f'<a href="{lk.get("atlas_en", "#")}">EN</a> / '
                 f'<a href="{lk.get("atlas_cn", "#")}">CN</a>')
        tag = "" if e.get("status") == "built" else f' <span class="plan">({esc(t["descriptive"])})</span>'
        rows.append(
            f'<tr><td class="built">{esc(e["name"])}</td>'
            f'<td>{esc(e.get("work_type", ""))}</td>'
            f'<td>{esc(", ".join(e.get("usage_methods", [])))}</td>'
            f'<td>{esc(", ".join(e.get("annotation_types", [])))}</td>'
            f'<td>{ann_s}</td><td>{clu_s}</td>'
            f'<td>{esc(e.get("downloadable", e.get("data_access", "")))}</td>'
            f'<td>{esc(e.get("license", "n/a"))}</td>'
            f'<td>{atlas}{tag}</td></tr>'
        )
    for p in planned:
        ar = p.get("arxiv", "")
        name = (f'<a href="{ar}">{esc(p["name"])}</a>' if ar.startswith("http") else esc(p["name"]))
        rows.append(
            f'<tr><td class="plan">{name}</td>'
            f'<td>{esc(p.get("category", ""))}</td>'
            f'<td>{esc(", ".join(p.get("usage_methods", [])))}</td>'
            f'<td>{esc(", ".join(p.get("annotation_types", [])))}</td>'
            f'<td>n/a</td><td>n/a</td>'
            f'<td>{esc(p.get("downloadable", p.get("data_access", "")))}</td>'
            f'<td>{esc(p.get("license", "n/a"))}</td>'
            f'<td class="plan">planned</td></tr>'
        )
    return "\n".join(rows)


def roadmap_html(planned, t, lang):
    if not planned:
        return f'<p class="note">{esc(t["road_none"])}</p>'
    out = []
    by_cat = {}
    for p in planned:
        by_cat.setdefault(p.get("category", "method"), []).append(p)
    for cat in CAT_ORDER:
        items = by_cat.get(cat, [])
        if not items:
            continue
        out.append(f'<h3>{esc(cat_label(cat, lang))}</h3>')
        for p in items:
            ar = p.get("arxiv", "")
            name = (f'<a href="{ar}">{esc(p["name"])}</a>' if ar.startswith("http") else esc(p["name"]))
            chips = " ".join(chip(u) for u in p.get("usage_methods", []))
            chips += " " + " ".join(f'<span class="chip alt">{esc(a)}</span>'
                                    for a in p.get("annotation_types", []))
            suit = p.get("suitability", "")
            out.append(
                f'<div class="rm"><b>{name}</b> {chips}<br>'
                f'<span class="ef">{esc(p.get("focus", ""))}</span><br>'
                f'<span class="meta">{esc(t["road_access"])}: {esc(p.get("downloadable", p.get("data_access", "n/a")))} '
                f'&middot; {esc(t["road_license"])}: {esc(p.get("license", "n/a"))} '
                f'&middot; {esc(suit)}</span></div>'
            )
    return "\n".join(out)


def jacc(a, b):
    if not a or not b:
        return 0.0
    return len(a & b) / len(a | b)


def build_crosswork(built, t):
    works = [e for e in built if e.get("_stats")]
    if len(works) < 2:
        return f'<p class="note">{esc(t["cross_none"])}</p>'
    # work x verb-family coverage matrix (share of annotations per verb category)
    totals = {}
    for e in works:
        for name, cnt in e["_stats"].get("verb_category_dist", []):
            totals[name] = totals.get(name, 0) + cnt
    cats = [c for c, _ in sorted(totals.items(), key=lambda x: -x[1])]
    head = "".join(f'<th class="num">{esc(c)}</th>' for c in cats)
    rows = []
    for e in works:
        d = dict(e["_stats"].get("verb_category_dist", []))
        tot = sum(d.values()) or 1
        cells = []
        for c in cats:
            share = d.get(c, 0) / tot
            alpha = min(0.82, share * 2.6)
            cells.append(f'<td class="num" style="background:rgba(31,78,155,{alpha:.2f})">'
                         f'{share * 100:.0f}</td>')
        rows.append(f'<tr><td class="lab">{esc(e["name"])}</td>{"".join(cells)}</tr>')
    matrix = (f'<div class="minihead">{esc(t["cross_matrix"])}</div>'
              f'<div class="tablewrap"><table class="dtable"><thead><tr><th>{esc(t["th_work"])}</th>'
              f'{head}</tr></thead><tbody>{"".join(rows)}</tbody></table></div>')
    # granularity contrast
    mls = [(e["name"], round(e["_stats"]["length"]["tokens_mean"], 1)) for e in works]
    gran = (f'<div class="minihead">{esc(t["cross_gran"])}</div>'
            + A.bar_rows([(n, int(round(v))) for n, v in mls], color="var(--accent2)"))
    # lexical overlap on top-25 class keys
    def keys(e, field):
        return set(k for k, _ in e["_stats"].get(field, [])[:25])
    ov = []
    for i in range(len(works)):
        for j in range(i + 1, len(works)):
            a, b = works[i], works[j]
            ov.append(f'<tr><td class="lab">{esc(a["name"])} vs {esc(b["name"])}</td>'
                      f'<td class="num">{jacc(keys(a, "verb_top"), keys(b, "verb_top")):.2f}</td>'
                      f'<td class="num">{jacc(keys(a, "noun_top"), keys(b, "noun_top")):.2f}</td></tr>')
    overlap = (f'<div class="minihead">{esc(t["cross_overlap"])}</div>'
               f'<div class="tablewrap"><table class="dtable"><thead><tr><th>{esc(t["cross_pair"])}</th>'
               f'<th class="num">{esc(t["cross_verbs"])}</th><th class="num">{esc(t["cross_nouns"])}</th></tr></thead>'
               f'<tbody>{"".join(ov)}</tbody></table></div>')
    # usage-method x annotation-style map
    um = []
    for e in works:
        chips = (" ".join(chip(u) for u in e.get("usage_methods", []))
                 + " " + " ".join(f'<span class="chip alt">{esc(a)}</span>'
                                   for a in e.get("annotation_types", [])))
        um.append(f'<div class="rm"><b>{esc(e["name"])}</b> {chips}</div>')
    umap = f'<div class="minihead">{esc(t["cross_usage"])}</div>' + "".join(um)
    return (matrix + '<div class="twocol"><div>' + gran + '</div><div>' + overlap
            + '</div></div>' + umap)


def cards_grouped(entry_list, t, lang):
    """Cards grouped by usage tier, for a given subset of entries."""
    tiers = {}
    for e in entry_list:
        tiers.setdefault(primary_tier(e), []).append(e)
    out = []
    for tk in TIER_ORDER:
        if tk in tiers:
            out.append(f'<h3>{esc(tier_label(tk, lang))}</h3><div class="cards">'
                       + "".join(entry_card(e, t) for e in tiers[tk]) + '</div>')
    return "".join(out)


def build_index(entries, planned, lang):
    t = INDEX_I18N[lang]
    built = [e for e in entries if e.get("status") == "built"]
    desc = [e for e in entries if e.get("status") == "descriptive"]
    n_built, n_desc, n_plan = len(built), len(desc), len(planned)

    built_cards = cards_grouped(built, t, lang) or f'<p class="note">{esc(t["cross_none"])}</p>'
    desc_cards = cards_grouped(desc, t, lang) or ""
    cross = build_crosswork(entries, t) if n_built >= 2 else f'<p class="note">{esc(t["cross_none"])}</p>'
    lang_attr = "zh" if lang == "cn" else "en"

    header = (
        f'<!DOCTYPE html>\n<html lang="{lang_attr}"><head><meta charset="utf-8"/>'
        '<meta name="viewport" content="width=device-width, initial-scale=1"/>'
        f'<title>{esc(t["title"])}</title>'
        f'<style>{CSS}</style></head><body><div class="wrap">'
        '<header class="card"><div class="toprow">'
        f'<div class="brand">{esc(t["brand"])}</div>'
        f'<div class="langtoggle"><a href="{t["other_file"]}">{esc(t["other_name"])}</a></div></div>'
        f'<h1>{esc(t["title"])}</h1>'
        f'<p class="focus">{esc(t["focus"])}</p>'
        f'<div class="kc"><div><div class="kcv">{n_built}</div><div class="kcl">{esc(t["k_built"])}</div></div>'
        f'<div><div class="kcv">{n_desc}</div><div class="kcl">{esc(t["k_desc"])}</div></div>'
        f'<div><div class="kcv">{n_plan}</div><div class="kcl">{esc(t["k_plan"])}</div></div>'
        f'<div><div class="kcv">{BUILD_DATE}</div><div class="kcl">{esc(t["k_gen"])}</div></div></div>'
        f'<p class="note">{esc(t["note"])}</p></header>'
    )
    survey = (
        f'<div class="tablewrap"><table><thead><tr><th>{esc(t["th_work"])}</th><th>{esc(t["th_type"])}</th>'
        f'<th>{esc(t["th_usage"])}</th><th>{esc(t["th_annot"])}</th><th>{esc(t["th_ann"])}</th>'
        f'<th>{esc(t["th_clusters"])}</th><th>{esc(t["th_data"])}</th>'
        f'<th>{esc(t["th_license"])}</th><th>{esc(t["th_atlas"])}</th></tr></thead><tbody>'
        f'{survey_rows_html(entries, planned, t)}</tbody></table></div>'
    )

    # Section order: built atlases first, cross-work comparison second, then the
    # descriptive entries, the full survey table, and the roadmap.
    sections = [(t["s_built"], built_cards), (t["s_cross"], cross)]
    if desc_cards:
        sections.append((t["s_desc"], desc_cards))
    sections.append((t["s_survey"], survey))
    sections.append((t["s_road"], roadmap_html(planned, t, lang)))
    body = "".join(
        f'<section class="card"><h2><span class="snum">{i:02d}</span>{esc(title)}</h2>{html_}</section>'
        for i, (title, html_) in enumerate(sections, 1)
    )
    footer = f'<footer class="card"><p class="note">{t["footer"].format(date=BUILD_DATE)}</p></footer>'
    return header + body + footer + '</div></body></html>'


# -------------------------------------------------------------------- README
def md_survey(entries, planned):
    head = ("| Work | Type | Usage methods | Annotation types | Annotations | Clusters "
            "| Data access | License | Atlas |\n"
            "|---|---|---|---|---|---|---|---|---|\n")
    lines = []
    for e in entries:
        c = e.get("_counts", {})
        lk = e.get("links", {})
        ann = c.get("annotations")
        ann_s = f"{ann:,}" if isinstance(ann, int) else "n/a"
        clu = c.get("clusters")
        clu_s = f"{clu}" if isinstance(clu, int) else "n/a"
        atlas = f'[EN]({lk.get("atlas_en","#")}) / [CN]({lk.get("atlas_cn","#")})'
        if e.get("status") != "built":
            atlas += " (descriptive)"
        lines.append("| {n} | {t} | {u} | {a} | {ann} | {cl} | {d} | {lic} | {at} |".format(
            n=e["name"], t=e.get("work_type", ""), u=", ".join(e.get("usage_methods", [])),
            a=", ".join(e.get("annotation_types", [])), ann=ann_s, cl=clu_s,
            d=e.get("downloadable", e.get("data_access", "")),
            lic=e.get("license", "n/a"), at=atlas))
    for p in planned:
        ar = p.get("arxiv", "")
        nm = f'[{p["name"]}]({ar})' if ar.startswith("http") else p["name"]
        lines.append("| {n} | {t} | {u} | {a} | n/a | n/a | {d} | {lic} | planned |".format(
            n=nm, t=p.get("category", ""), u=", ".join(p.get("usage_methods", [])),
            a=", ".join(p.get("annotation_types", [])),
            d=p.get("downloadable", p.get("data_access", "")), lic=p.get("license", "n/a")))
    return head + "\n".join(lines) + "\n"


def md_roadmap(planned):
    if not planned:
        return "_Roadmap empty. Populate roadmap.json and re-run build_atlas_index.py._\n"
    by_cat = {}
    for p in planned:
        by_cat.setdefault(p.get("category", "method"), []).append(p)
    out = []
    for cat in CAT_ORDER:
        items = by_cat.get(cat, [])
        if not items:
            continue
        out.append(f"\n### {CAT_LABEL.get(cat, cat)}\n")
        for p in items:
            ar = p.get("arxiv", "")
            nm = f'[{p["name"]}]({ar})' if ar.startswith("http") else p["name"]
            out.append(
                f"- **{nm}** ({p.get('venue','')}) "
                f"[{', '.join(p.get('usage_methods', []))} | "
                f"{', '.join(p.get('annotation_types', []))}]  \n"
                f"  {p.get('focus','')}  \n"
                f"  access: {p.get('downloadable', p.get('data_access','n/a'))} "
                f"| license: {p.get('license','n/a')} | {p.get('suitability','')}")
    return "\n".join(out) + "\n"


def update_readme(entries, planned):
    path = os.path.join(HERE, "README.md")
    if not os.path.exists(path):
        print("README.md not found, skipping its update")
        return
    txt = open(path, encoding="utf-8").read()
    for tag, content in (("SURVEY", md_survey(entries, planned)),
                         ("ROADMAP", md_roadmap(planned))):
        start, end = f"<!-- {tag}:START -->", f"<!-- {tag}:END -->"
        if start in txt and end in txt:
            pre = txt.split(start)[0] + start + "\n"
            post = "\n" + end + txt.split(end)[1]
            txt = pre + content + post
    open(path, "w", encoding="utf-8").write(txt)


def main():
    entries = load_entries()
    planned = filter_planned(load_roadmap(), entries)
    for lang, fname in (("en", "index.html"), ("cn", "index_cn.html")):
        with open(os.path.join(HERE, fname), "w", encoding="utf-8") as fh:
            fh.write(build_index(entries, planned, lang))
    update_readme(entries, planned)
    nb = sum(1 for e in entries if e.get("status") == "built")
    nd = sum(1 for e in entries if e.get("status") == "descriptive")
    print(f"index.html + index_cn.html + README updated: {nb} built, {nd} descriptive, {len(planned)} planned")


if __name__ == "__main__":
    main()
